export default {
  list: [
    { id: 1, name: '素炒蘑菇' },
    { id: 2, name: '素炒芹菜' },
    { id: 3, name: '素炒豆角' },
    { id: 4, name: '醋溜土豆丝' },
    { id: 5, name: '醋溜白菜' },
    { id: 6, name: '银耳炒鸡蛋' },
    { id: 7, name: '凉拌木耳' },
    { id: 8, name: '买着吃' },
    { id: 9, name: '买肠子' },
    { id: 10, name: '红烧肉' },
    { id: 11, name: '尖椒炒鸡蛋' },
    { id: 12, name: '酱大骨' },
    { id: 13, name: '凉拌金针菇' },
    { id: 14, name: '麻婆豆腐' },
    { id: 15, name: '炖牛肉' },
    { id: 16, name: '鱼香肉丝' },
    { id: 17, name: '炒方便面' },
    { id: 18, name: '炒饭' },
    { id: 19, name: '炒饼' },
    { id: 20, name: '炒面' },
    { id: 21, name: '炒菜花' },
    { id: 22, name: '炒萝卜丝' },
    { id: 23, name: '西红柿炒鸡蛋' },
    { id: 24, name: '懵鸡蛋' },
    { id: 25, name: '摊鸡蛋' },
    { id: 26, name: '土豆炖豆角' },
    { id: 27, name: '大锅菜' },
    { id: 28, name: '烧饼自选套餐' },
    { id: 29, name: '煮方便面-晚饭' },
    { id: 30, name: '鱼香肉丝' },
    // { id: 31, name: '鱼香肉丝' },
    // { id: 32, name: '鱼香肉丝' },
    // { id: 33, name: '鱼香肉丝' },
    // { id: 34, name: '鱼香肉丝' },
    // { id: 35, name: '鱼香肉丝' },
    // { id: 36, name: '鱼香肉丝' },
  ]
}